version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:latest
    restart: always

  airflow-webserver:
    image: apache/airflow:latest
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags  # Dynamic DAGs Path
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: >
      /bin/bash -c "pip install dvc &&
      airflow db init &&
      airflow webserver"
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]

  airflow-scheduler:
    image: apache/airflow:latest
    restart: always
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: >
      /bin/bash -c "pip install dvc &&
      airflow scheduler"

  airflow-worker:
    image: apache/airflow:latest
    restart: always
    depends_on:
      - airflow-webserver
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: >
      /bin/bash -c "pip install dvc &&
      airflow celery worker"
